version: "3"
services:
  app-build:
    image: index.docker.io/appsmith/appsmith-ee
    container_name: app-build
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.appsmith.rule=Host(`build.kocur.app`)
      - traefik.http.routers.appsmith.tls=true
      - traefik.http.routers.appsmith.tls.certresolver=letsencrypt
      - traefik.http.services.appsmith.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
    name: proxy
