version: "3"
services:
  app-build:
    image: index.docker.io/appsmith/appsmith-ee
    container_name: app-build
    ports:
      - "1281:1281"
      - "1282:1282"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-build.rule=Host(`build.kocur.app`)
      - traefik.http.routers.app-build.tls=true
      - traefik.http.routers.app-build.tls.certresolver=letsencrypt
      - traefik.http.services.app-build.loadbalancer.server.port=1281
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
    name: proxy
